# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
#    exceed four million, find the sum of the even-valued terms.


def even_valued_number(x)
  fib_array = [0,1]
  x.times do
    fib_array << fib_array[-1] + fib_array[-2]
  end
 fib_array.find_all{ |number| number % 2 == 0}.reduce(:+)
end

# Answer: 4613732
